target_and_collection/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_view, name='dashboard_view'),
]

target_and_collection/organization/urls.py
from django.urls import path
from . import views

app_name = 'organization'

urlpatterns = [
    path('departments/', views.department_list, name='department_list'),
    path('departments/create/', views.department_create, name='department_create'),
    path('departments/<int:pk>/update/', views.department_update, name='department_update'),
    path('departments/<int:pk>/delete/', views.department_delete, name='department_delete'),

    path('subdepartments/', views.subdepartment_list, name='subdepartment_list'),
    path('subdepartments/create/', views.subdepartment_create, name='subdepartment_create'),
    path('subdepartments/<int:pk>/update/', views.subdepartment_update, name='subdepartment_update'),
    path('subdepartments/<int:pk>/delete/', views.subdepartment_delete, name='subdepartment_delete'),

    path('rules/', views.rule_list, name='rule_list'),
    path('rules/create/', views.rule_create, name='rule_create'),
    path('rules/<int:pk>/update/', views.rule_update, name='rule_update'),
    path('rules/<int:pk>/delete/', views.rule_delete, name='rule_delete'),
    path('api/get_model_fields/', views.get_model_fields, name='get_model_fields'),
]

target_and_collection/target_and_collection/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('target/', include('target.urls')),
    path('collection/', include('collection.urls')),
    path('organization/', include('organization.urls')),
    path('dashboard/', include('dashboard.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

target_and_collection/organization/models.py
from django.db import models

# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class SubDepartment(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f"{self.department.name} - {self.name}"

# Rule System Models
class Rule(models.Model):
    """
    A rule that can be applied to models to enforce validation.
    """
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Condition(models.Model):
    """
    A condition that must be met for a rule to be satisfied.
    """
    OPERATOR_CHOICES = [
        ('eq', 'Equals'),
        ('neq', 'Not Equals'),
        ('gt', 'Greater Than'),
        ('gte', 'Greater Than or Equal'),
        ('lt', 'Less Than'),
        ('lte', 'Less Than or Equal'),
        ('contains', 'Contains'),
        ('in', 'In'),
        ('not_in', 'Not In'),
        ('belongs_to', 'Belongs To'),
    ]

    rule = models.ForeignKey(Rule, on_delete=models.CASCADE, related_name='conditions')
    field_name = models.CharField(max_length=100, help_text="The name of the field to check")
    operator = models.CharField(max_length=20, choices=OPERATOR_CHOICES)
    value = models.CharField(max_length=255, help_text="The value to compare against")
    negate = models.BooleanField(default=False, help_text="Negate the condition")

    def __str__(self):
        return f"{self.field_name} {self.get_operator_display()} {self.value}"

class RuleTarget(models.Model):
    """
    Specifies which models or fields a rule applies to.
    """
    MODEL_CHOICES = [
        ('organization.Department', 'Department'),
        ('organization.SubDepartment', 'SubDepartment'),
        ('target.Target', 'Target'),
        ('collection.Collection', 'Collection'),
    ]

    rule = models.ForeignKey(Rule, on_delete=models.CASCADE, related_name='targets')
    model_name = models.CharField(max_length=100, choices=MODEL_CHOICES)
    field_name = models.CharField(max_length=100, blank=True, help_text="Specific field to apply rule to (leave blank for all fields)")

    def __str__(self):
        return f"{self.model_name}.{self.field_name if self.field_name else '*'}"

target_and_collection/organization/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.apps import apps
from .models import Department, SubDepartment, Rule, Condition, RuleTarget


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class SubDepartmentForm(forms.ModelForm):
    class Meta:
        model = SubDepartment
        fields = ['department', 'name']
        widgets = {
            'department': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class RuleForm(forms.ModelForm):
    class Meta:
        model = Rule
        fields = ['name', 'description', 'is_active']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class ConditionForm(forms.ModelForm):
    class Meta:
        model = Condition
        fields = ['field_name', 'operator', 'value']
        widgets = {
            'field_name': forms.TextInput(attrs={'class': 'form-control'}),
            'operator': forms.Select(attrs={'class': 'form-control'}),
            'value': forms.TextInput(attrs={'class': 'form-control'}),
        }

ConditionFormSet = inlineformset_factory(Rule, Condition, form=ConditionForm, extra=1, can_delete=True)


class RuleTargetForm(forms.ModelForm):
    model_name = forms.ChoiceField(required=True, widget=forms.Select(attrs={'class': 'form-control model-select'}))
    field_name = forms.ChoiceField(choices=[], required=True, widget=forms.Select(attrs={'class': 'form-control field-select'}))

    class Meta:
        model = RuleTarget
        fields = ['rule', 'model_name', 'field_name']
        widgets = {
            'rule': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['model_name'].choices = self.get_model_choices()

    def get_model_choices(self):
        model_choices = []
        for model in apps.get_models():
            model_choices.append((f'{model._meta.app_label}.{model._meta.model_name}', model._meta.verbose_name.title()))
        return sorted(model_choices, key=lambda x: x[1])

RuleTargetFormSet = inlineformset_factory(Rule, RuleTarget, form=RuleTargetForm, extra=1, can_delete=True)

target_and_collection/organization/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.apps import apps
from .models import Department, SubDepartment, Rule, Condition, RuleTarget
from .forms import DepartmentForm, SubDepartmentForm, RuleForm, ConditionForm, RuleTargetForm, ConditionFormSet, RuleTargetFormSet


def department_list(request):
    departments = Department.objects.all()
    return render(request, 'organization/department_list.html', {'departments': departments})


def department_create(request):
    if request.method == 'POST':
        form = DepartmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('organization:department_list')
    else:
        form = DepartmentForm()
    return render(request, 'organization/department_form.html', {'form': form})


def department_update(request, pk):
    department = get_object_or_404(Department, pk=pk)
    if request.method == 'POST':
        form = DepartmentForm(request.POST, instance=department)
        if form.is_valid():
            form.save()
            return redirect('organization:department_list')
    else:
        form = DepartmentForm(instance=department)
    return render(request, 'organization/department_form.html', {'form': form})


def department_delete(request, pk):
    department = get_object_or_404(Department, pk=pk)
    if request.method == 'POST':
        department.delete()
        return redirect('organization:department_list')
    return render(request, 'organization/department_confirm_delete.html', {'department': department})


def subdepartment_list(request):
    subdepartments = SubDepartment.objects.all()
    return render(request, 'organization/subdepartment_list.html', {'subdepartments': subdepartments})


def subdepartment_create(request):
    if request.method == 'POST':
        form = SubDepartmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('organization:subdepartment_list')
    else:
        form = SubDepartmentForm()
    return render(request, 'organization/subdepartment_form.html', {'form': form})


def subdepartment_update(request, pk):
    subdepartment = get_object_or_404(SubDepartment, pk=pk)
    if request.method == 'POST':
        form = SubDepartmentForm(request.POST, instance=subdepartment)
        if form.is_valid():
            form.save()
            return redirect('organization:subdepartment_list')
    else:
        form = SubDepartmentForm(instance=subdepartment)
    return render(request, 'organization/subdepartment_form.html', {'form': form})


def subdepartment_delete(request, pk):
    subdepartment = get_object_or_404(SubDepartment, pk=pk)
    if request.method == 'POST':
        subdepartment.delete()
        return redirect('organization:subdepartment_list')
    return render(request, 'organization/subdepartment_confirm_delete.html', {'subdepartment': subdepartment})


def rule_list(request):
    rules = Rule.objects.all()
    return render(request, 'organization/rule_list.html', {'rules': rules})


def rule_create(request):
    if request.method == 'POST':
        form = RuleForm(request.POST)
        condition_formset = ConditionFormSet(request.POST, instance=Rule())
        rule_target_formset = RuleTargetFormSet(request.POST, instance=Rule())
        if form.is_valid() and condition_formset.is_valid() and rule_target_formset.is_valid():
            rule = form.save()
            condition_formset.instance = rule
            condition_formset.save()
            rule_target_formset.instance = rule
            rule_target_formset.save()
            return redirect('organization:rule_list')
    else:
        form = RuleForm()
        condition_formset = ConditionFormSet(instance=Rule())
        rule_target_formset = RuleTargetFormSet(instance=Rule())
    return render(request, 'organization/rule_form.html', {
        'form': form,
        'condition_formset': condition_formset,
        'rule_target_formset': rule_target_formset
    })


def rule_update(request, pk):
    rule = get_object_or_404(Rule, pk=pk)
    if request.method == 'POST':
        form = RuleForm(request.POST, instance=rule)
        condition_formset = ConditionFormSet(request.POST, instance=rule)
        rule_target_formset = RuleTargetFormSet(request.POST, instance=rule)
        if form.is_valid() and condition_formset.is_valid() and rule_target_formset.is_valid():
            form.save()
            condition_formset.save()
            rule_target_formset.save()
            return redirect('organization:rule_list')
    else:
        form = RuleForm(instance=rule)
        condition_formset = ConditionFormSet(instance=rule)
        rule_target_formset = RuleTargetFormSet(instance=rule)
    return render(request, 'organization/rule_form.html', {
        'form': form,
        'condition_formset': condition_formset,
        'rule_target_formset': rule_target_formset
    })


def rule_delete(request, pk):
    rule = get_object_or_404(Rule, pk=pk)
    if request.method == 'POST':
        rule.delete()
        return redirect('organization:rule_list')
    return render(request, 'organization/rule_confirm_delete.html', {'rule': rule})

def get_model_fields(request):
    model_name = request.GET.get('model_name')
    app_label, model_name = model_name.split('.')
    try:
        model = apps.get_model(app_label, model_name)
        fields = []
        for field in model._meta.get_fields():
            if hasattr(field, 'verbose_name'):
                fields.append({'name': field.name, 'verbose_name': field.verbose_name})
            else:
                fields.append({'name': field.name, 'verbose_name': field.name})
        return JsonResponse(fields, safe=False)
    except LookupError:
        return JsonResponse([], safe=False)

target_and_collection/organization/templates/organization/department_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Department{% endblock %}

{% block content %}
<h1>Delete Department</h1>
<p>Are you sure you want to delete "{{ department.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm Delete</button>
    <a href="{% url 'organization:department_list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

target_and_collection/organization/templates/organization/department_form.html
{% extends 'base.html' %}

{% block title %}{{ action }} Department{% endblock %}

{% block content %}
<h1>{{ action }} Department</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Save</button>
    <a href="{% url 'organization:department_list' %}" class="btn btn-danger">Cancel</a>
</form>
{% endblock %}

target_and_collection/organization/templates/organization/department_list.html
{% extends 'base.html' %}

{% block title %}Departments{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="mb-4">Departments</h1>
    <a href="{% url 'organization:department_create' %}" class="btn btn-primary">Add Department</a>
</div>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for department in departments %}
            <tr>
                <td>{{ department.name }}</td>
                <td>
                    <a href="{% url 'organization:department_update' department.pk %}" class="btn btn-success btn-sm">Edit</a>
                    <a href="{% url 'organization:department_delete' department.pk %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="2" class="text-center">No departments found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

target_and_collection/organization/templates/organization/rule_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Rule{% endblock %}

{% block content %}
<h1>Delete Rule</h1>
<p>Are you sure you want to delete "{{ rule.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm Delete</button>
    <a href="{% url 'organization:rule_list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

target_and_collection/organization/templates/organization/rule_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    {% if form.instance.pk %}
        Edit Rule
    {% else %}
        Create Rule
    {% endif %}
{% endblock %}

{% block content %}
    <h1 class="mb-4">
        {% if form.instance.pk %}
            Edit Rule
        {% else %}
            Create Rule
        {% endif %}
    </h1>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                {{ field }}
                {% if field.help_text %}
                    <div class="form-text">{{ field.help_text }}</div>
                {% endif %}
                {% for error in field.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}

        <h3>Conditions</h3>
        <div id="condition-formset-container">
            {{ condition_formset.management_form }}
            {% for form in condition_formset %}
                <div class="condition-formset-row mb-3 p-3 border rounded">
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add-condition" class="btn btn-secondary mb-3">Add Condition</button>

        <h3>Rule Targets</h3>
        <div id="ruletarget-formset-container">
            {{ rule_target_formset.management_form }}
            {% for form in rule_target_formset %}
                <div class="ruletarget-formset-row mb-3 p-3 border rounded">
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add-ruletarget" class="btn btn-secondary mb-3">Add Rule Target</button>

        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'organization:rule_list' %}" class="btn btn-danger">Cancel</a>
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            function updateFieldChoices(modelSelect, fieldSelect) {
                const modelName = modelSelect.value;
                console.log('Selected modelName:', modelName); // Debugging line
                if (modelName) {
                    fetch(`/organization/api/get_model_fields/?model_name=${modelName}`)
                        .then(response => {
                            if (!response.ok) {
                                throw new Error(`HTTP error! status: ${response.status}`);
                            }
                            return response.json();
                        })
                        .then(data => {
                            fieldSelect.innerHTML = ''; // Clear existing options
                            data.forEach(field => {
                                const option = document.createElement('option');
                                option.value = field.name;
                                option.textContent = field.verbose_name;
                                fieldSelect.appendChild(option);
                            });
                        })
                        .catch(error => console.error('Error fetching model fields:', error));
                } else {
                    fieldSelect.innerHTML = '<option value="">---------</option>'; // Add a default option
                }
            }

            document.querySelectorAll('.ruletarget-formset-row').forEach(row => {
                const modelSelect = row.querySelector('.model-select');
                const fieldSelect = row.querySelector('.field-select');
                if (modelSelect && fieldSelect) {
                    // Initial load
                    updateFieldChoices(modelSelect, fieldSelect);

                    // Event listener for change
                    modelSelect.addEventListener('change', function() {
                        updateFieldChoices(this, fieldSelect);
                    });
                }
            });

            // Add formset row functionality (simplified for brevity, assuming you have this)
            const addRuleTargetButton = document.getElementById('add-ruletarget');
            const ruleTargetFormsetContainer = document.getElementById('ruletarget-formset-container');
            let ruleTargetFormCount = ruleTargetFormsetContainer.querySelectorAll('.ruletarget-formset-row').length;

            addRuleTargetButton.addEventListener('click', function() {
                const emptyForm = ruleTargetFormsetContainer.querySelector('.ruletarget-formset-row').cloneNode(true);
                emptyForm.innerHTML = emptyForm.innerHTML.replace(/__prefix__/g, ruleTargetFormCount);
                ruleTargetFormsetContainer.appendChild(emptyForm);
                ruleTargetFormCount++;
                document.getElementById('id_rule_target_set-TOTAL_FORMS').value = ruleTargetFormCount;

                const newModelSelect = emptyForm.querySelector('.model-select');
                const newFieldSelect = emptyForm.querySelector('.field-select');
                if (newModelSelect && newFieldSelect) {
                    newModelSelect.addEventListener('change', function() {
                        updateFieldChoices(this, newFieldSelect);
                    });
                    updateFieldChoices(newModelSelect, newFieldSelect); // Initialize new row
                }
            });
        });
    </script>
{% endblock %}

target_and_collection/organization/templates/organization/rule_list.html
{% extends 'base.html' %}

{% block title %}Rules{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="mb-4">Rules</h1>
    <a href="{% url 'organization:rule_create' %}" class="btn btn-primary">Add New Rule</a>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Priority</th>
                <th>Department</th>
                <th>SubDepartment</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for rule in rules %}
            <tr>
                <td>{{ rule.name }}</td>
                <td>{{ rule.description }}</td>
                <td>{{ rule.priority }}</td>
                <td>{{ rule.department.name }}</td>
                <td>{{ rule.sub_department.name }}</td>
                <td>
                    <a href="{% url 'organization:rule_update' rule.pk %}" class="btn btn-success btn-sm">Edit</a>
                    <a href="{% url 'organization:rule_delete' rule.pk %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6" class="text-center">No rules found.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

target_and_collection/organization/templates/organization/subdepartment_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete SubDepartment{% endblock %}

{% block content %}
<h1>Delete SubDepartment</h1>
<p>Are you sure you want to delete "{{ subdepartment.name }}" from department "{{ subdepartment.department.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm Delete</button>
    <a href="{% url 'organization:subdepartment_list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

target_and_collection/organization/templates/organization/subdepartment_form.html
{% extends 'base.html' %}

{% block title %}
    {% if form.instance.pk %}
        Edit SubDepartment
    {% else %}
        Create SubDepartment
    {% endif %}
{% endblock %}

{% block content %}
    <h1>
        {% if form.instance.pk %}
            Edit SubDepartment
        {% else %}
            Create SubDepartment
        {% endif %}
    </h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'organization:subdepartment_list' %}" class="btn btn-danger">Cancel</a>
    </form>
{% endblock %}

target_and_collection/organization/templates/organization/subdepartment_list.html
{% extends 'base.html' %}

{% block title %}SubDepartments{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="mb-4">SubDepartments</h1>
    <a href="{% url 'organization:subdepartment_create' %}" class="btn btn-primary">Add New SubDepartment</a>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Department</th>
                <th>Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for subdepartment in subdepartments %}
            <tr>
                <td>{{ subdepartment.department.name }}</td>
                <td>{{ subdepartment.name }}</td>
                <td>
                    <a href="{% url 'organization:subdepartment_update' subdepartment.pk %}" class="btn btn-success btn-sm">Edit</a>
                    <a href="{% url 'organization:subdepartment_delete' subdepartment.pk %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3" class="text-center">No subdepartments found.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}